sudo: required
dist: trusty
language: generic

env:
  matrix:
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="kinetic" PRERELEASE=true OS_NAME=debian OS_CODE_NAME=jessie

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
