language: generic
services:
  - docker 

env:
  matrix:
    - ROS_DISTRO="kinetic" PRERELEASE=true

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
