sudo: required 
dist: trusty 
language: generic 
env:
  matrix:
    - ROS_DISTRO="jade"    ROS_REPO=ros
    - ROS_DISTRO="jade"    ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros ABICHECK=true FALLBACK_BRANCH=0.7.1
    - ROS_DISTRO="lunar"   ROS_REPO=ros-shadow-fixed
install:
  - git clone --depth=1 https://github.com/ipa-mdl/industrial_ci.git -b feature/abi-check .ci_config
script: 
  - .ci_config/travis.sh
