sudo: required
dist: trusty
language: generic

env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

install:
  - git clone https://github.com/ipa-mdl/industrial_ci.git -b fix/install-space .ci_config
script:
  - .ci_config/travis.sh
