language: generic
services:
  - docker

env:
  global:
    - ROS_DISTRO="melodic" BUILDER=colcon ROS_REPO=ros AFTER_SCRIPT='cd $target_ws && rosenv && colcon build --event-handlers status- desktop_notification- --cmake-target-skip-unavailable --cmake-target roslint' 
  matrix:
    - ICI_CLONE="https://github.com/ros-industrial/industrial_ci.git -b master"
    - ICI_CLONE="https://github.com/ipa-mdl/industrial_ci.git -b fix-master-rosenv"
    - ICI_CLONE="https://github.com/ipa-mdl/industrial_ci.git -b fix-master-rosenv" AFTER_SCRIPT='builder_run_build "$target_ws/install" "$target_ws" --cmake-target-skip-unavailable --cmake-target roslint'
install:
  - git clone --quiet --depth=1 $ICI_CLONE .industrial_ci
script:
  - .industrial_ci/travis.sh
