sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
env:
  matrix:
    - ROS_DISTRO="indigo" PRERELEASE=true
    - ROS_DISTRO="jade" PRERELEASE=true
install:
  - git clone https://github.com/ipa-mdl/industrial_ci.git .ci_config -b prerelease-from-src
script: 
  - source .ci_config/travis.sh
